
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="lycanthropy" #mandatory

version="1.15.2-1.0.0" #mandatory

displayName="Lycanthropy+" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thank you to Technovision for your mod tutorial!" #optional

authors="atomicAxolotl" #optional

description='''
Werebeasts of all sorts.
'''

[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[31,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
